server:
  port: 8090
#  ssl:
#    key-store: 3984126_www.qsssss.com.pfx
#    key-store-type: PKCS12
#    key-store-password: wjv1atcY
#spring.datasource.du

spring:
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name:
      url: jdbc:mysql://${DB_MYSQL_IP}:${DB_MYSQL_PORT}/mini?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
#  mvc:
#    static-path-pattern: /images/*
#  resources:
#    static-locations: ${StaticResource}
#  data:
#    elasticsearch:
#      cluster-name:
#      repositories:
#        enabled: true
#      client:
#        reactive:
#          endpoints: http://39.100.150.192:9200


mybatis:
  configuration:
    type-aliases-package: com.info.share.mini.entity
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true

# https://
wechat:
  code2SessionUrl: api.weixin.qq.com/sns/jscode2session?appid=APPID&secret=SECRET&js_code=JSCODE&grant_type=authorization_code
  accessTokenUrl: api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET
  appId: wx3ab7d45aeb09ce37
  appSecret: 73b54c99840affc65387b737a7d9f621
  appKey: xxxxx
  mchId: xxxx
  buildOrder: api.mch.weixin.qq.com/pay/unifiedorder
  QRImagePath: ${StaticResource}/QRImages/
  nginxUrl: https://www.qsssss.com/static/QRImages/

#debug: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#logging:
#  pattern:
#    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{15} - %msg%n'
#    file: '%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{15} - %msg%n'
#  file:
#    name: log/log.out